### ISSUE TITLE
Parallel run sometimes causes the driver to open already opened device

### ISSUE THREAD

**Issue by igorstd7** [Project-Quantum/Quantum#18]
When user run the cucumber tests in parallel, sometimes driver tries to open the device that already used by another test thread, so the test is ignored with next output:
Unable to create driver instance in 1st attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Failed to execute command handset open: Cannot open device 9A90117A5FF7AEB655944A1D7FA8C70F3C2C81BD for user test_automation@gmail.com, device is in use.

Steps to reproduce:
1. Create feature file with several test scenarios
2. Create xml suite which will run those scenarios in 2 tests, for one test set the "deviceName" parameter
3. Run the xml suite

**Comment by hadasshani** [comment]
open issue in qaf[https://github.com/qmetry/qaf/issues/59](url)

**Comment by kulin-sitwala** [comment]
I had a similar issue and I reported it to QAF because the above issue seems to be closed.

They replied that it maybe an issue from Perfecto Server end as it is delivering the same devices to two different threads. 

Please find response to this issue from QAF team: https://github.com/qmetry/qaf/issues/97

Can you please let me know what can we do about this?

This can be solved in two ways:

1. This can be solved from the server end.
2. We can handle it by customizing QAF jar in Quantum framework.

Please let me know what can be done here.

Thank You for your help in advance.

**Comment by kulin-sitwala** [comment]
I was facing this issue as driver.pluginType was defined as eclipse.

To execute tests in parallel, the eclipse plugin configurations needs to be disabled/commented in application.properties file.

You can close this issue from my end.
